# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: galaxy
steps:
- script: |
    set -x  
    ansible-galaxy collection build
    ansible-galaxy collection install *.tar.gz
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'playbook/demo.yml'
    inventoriesAgentMachine: 'hostList'
    inventoryHostListAgentMachine: 'localhost'
  env:
    ANSIBLE_CONFIG: $(Build.Repository.LocalPath)/ansible.cfg
- script: |
    ansible-galaxy collection publish --token $(galaxy_token)  *.tar.gz
